// ============================================================================
// MOCK DATA for Panel Demo
// All data is fake. No real IPs, credentials, or domain names.
// ============================================================================

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

export function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

export function findUserByCredentials(
  username: string,
  password: string
): (typeof users)[number] | undefined {
  if (password !== "demo" && password !== "admin123") return undefined;
  return users.find((u) => u.username === username);
}

// ---------------------------------------------------------------------------
// Users
// ---------------------------------------------------------------------------

export let users: any[] = [
  {
    id: "u1",
    username: "admin",
    role: "ADMIN" as const,
    buyerTag: null,
    palladiumApiKey: null,
    palladiumEmail: null,
    palladiumTelegram: null,
    totalDomains: 20,
    activeDomains: 12,
    inactiveDomains: 5,
    bannedDomains: 3,
    lastStatsUpdate: "2026-03-27T08:00:00.000Z",
    createdAt: "2025-11-01T10:00:00.000Z",
  },
  {
    id: "u2",
    username: "alex_operator",
    role: "OPERATOR" as const,
    buyerTag: "Alpha",
    palladiumApiKey: null,
    palladiumEmail: null,
    palladiumTelegram: null,
    totalDomains: 10,
    activeDomains: 7,
    inactiveDomains: 2,
    bannedDomains: 1,
    lastStatsUpdate: "2026-03-27T07:30:00.000Z",
    createdAt: "2025-12-15T14:20:00.000Z",
  },
  {
    id: "u3",
    username: "maria_ops",
    role: "OPERATOR" as const,
    buyerTag: "Bravo",
    palladiumApiKey: null,
    palladiumEmail: null,
    palladiumTelegram: null,
    totalDomains: 8,
    activeDomains: 5,
    inactiveDomains: 2,
    bannedDomains: 1,
    lastStatsUpdate: "2026-03-27T06:45:00.000Z",
    createdAt: "2026-01-10T09:00:00.000Z",
  },
];

// ---------------------------------------------------------------------------
// Servers
// ---------------------------------------------------------------------------

export let servers: any[] = [
  {
    id: "s1",
    name: "Production US-East",
    ip: "203.0.113.10",
    sshPort: 22,
    username: "deploy",
    authType: "key",
    passwordOrKey: "mock-ssh-key",
    tags: ["production", "us-east"],
    hostProvider: "VULTR",
    hostLocation: "New York",
    ipCost: 5,
    overallStatus: "ACTIVE",
    lastHeartbeat: "2026-03-27T09:55:00.000Z",
    createdAt: "2025-10-01T12:00:00.000Z",
    updatedAt: "2026-03-27T09:55:00.000Z",
  },
  {
    id: "s2",
    name: "Production EU-West",
    ip: "198.51.100.20",
    sshPort: 22,
    username: "deploy",
    authType: "key",
    passwordOrKey: "mock-ssh-key",
    tags: ["production", "eu-west"],
    hostProvider: "HSTQ",
    hostLocation: "Amsterdam",
    ipCost: 4.5,
    overallStatus: "ACTIVE",
    lastHeartbeat: "2026-03-27T09:54:30.000Z",
    createdAt: "2025-10-15T08:00:00.000Z",
    updatedAt: "2026-03-27T09:54:30.000Z",
  },
  {
    id: "s3",
    name: "Staging",
    ip: "192.0.2.30",
    sshPort: 2222,
    username: "root",
    authType: "password",
    passwordOrKey: "mock-password",
    tags: ["staging"],
    hostProvider: "Bitlaunch",
    hostLocation: "Frankfurt",
    ipCost: 3,
    overallStatus: "ACTIVE",
    lastHeartbeat: "2026-03-27T09:50:00.000Z",
    createdAt: "2026-01-05T16:30:00.000Z",
    updatedAt: "2026-03-27T09:50:00.000Z",
  },
];

// ---------------------------------------------------------------------------
// Offers
// ---------------------------------------------------------------------------

export let offers: any[] = [
  {
    id: "o1",
    name: "CardioBalance",
    folderName: "cardiobalance",
    geo: "LV",
    createdAt: "2025-11-20T10:00:00.000Z",
  },
  {
    id: "o2",
    name: "NeuroTonic Plus",
    folderName: "neurotonic",
    geo: "EE",
    createdAt: "2025-12-05T14:30:00.000Z",
  },
  {
    id: "o3",
    name: "JointFlex Pro",
    folderName: "jointflex",
    geo: "PL",
    createdAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "o4",
    name: "DiabControl",
    folderName: "diabcontrol",
    geo: "DE",
    createdAt: "2026-02-01T11:15:00.000Z",
  },
  {
    id: "o5",
    name: "SlimDetox",
    folderName: "slimdetox",
    geo: "LT",
    createdAt: "2026-02-18T16:45:00.000Z",
  },
];

// ---------------------------------------------------------------------------
// Domains (20 entries)
// ---------------------------------------------------------------------------

export let domains: any[] = [
  // --- Server s1 (Production US-East) - 8 domains ---
  {
    id: "d1",
    name: "healthvita-plus.com",
    serverId: "s1",
    status: "ACTIVE",
    buyerTag: "Alpha",
    geo: "LV",
    offerName: "CardioBalance",
    currentOfferId: "o1",
    offerFolder: "cardiobalance-a1b2c3",
    hasTag: true,
    hasConversion: true,
    isEmpty: false,
    healthStatus: "healthy",
    targetTraffic: 3200,
    botTraffic: 12,
    googleTag: "GT-XXXX1",
    conversion: "AW-XXXX1/abc",
    cfZoneId: "zn_fake_001",
    palladiumCampaignId: "pc_001",
    lastScannedAt: "2026-03-26T22:00:00.000Z",
    createdAt: "2025-12-01T10:00:00.000Z",
    updatedAt: "2026-03-26T22:00:00.000Z",
  },
  {
    id: "d2",
    name: "cardiobalance-shop.net",
    serverId: "s1",
    status: "ACTIVE",
    buyerTag: "Alpha",
    geo: "LV",
    offerName: "CardioBalance",
    currentOfferId: "o1",
    offerFolder: "cardiobalance-d4e5f6",
    hasTag: true,
    hasConversion: false,
    isEmpty: false,
    healthStatus: "healthy",
    targetTraffic: 2750,
    botTraffic: 8,
    googleTag: "GT-XXXX2",
    conversion: null,
    cfZoneId: "zn_fake_002",
    palladiumCampaignId: "pc_002",
    lastScannedAt: "2026-03-26T22:05:00.000Z",
    createdAt: "2025-12-05T11:30:00.000Z",
    updatedAt: "2026-03-26T22:05:00.000Z",
  },
  {
    id: "d3",
    name: "neuro-tonic.org",
    serverId: "s1",
    status: "ACTIVE",
    buyerTag: "Bravo",
    geo: "EE",
    offerName: "NeuroTonic Plus",
    currentOfferId: "o2",
    offerFolder: "neurotonic-g7h8i9",
    hasTag: true,
    hasConversion: true,
    isEmpty: false,
    healthStatus: "healthy",
    targetTraffic: 1800,
    botTraffic: 22,
    googleTag: "GT-XXXX3",
    conversion: "AW-XXXX3/def",
    cfZoneId: "zn_fake_003",
    palladiumCampaignId: "pc_003",
    lastScannedAt: "2026-03-26T22:10:00.000Z",
    createdAt: "2025-12-10T14:00:00.000Z",
    updatedAt: "2026-03-26T22:10:00.000Z",
  },
  {
    id: "d4",
    name: "jointflex-pro.com",
    serverId: "s1",
    status: "ACTIVE",
    buyerTag: "Alpha",
    geo: "PL",
    offerName: "JointFlex Pro",
    currentOfferId: "o3",
    offerFolder: "jointflex-j1k2l3",
    hasTag: false,
    hasConversion: false,
    isEmpty: false,
    healthStatus: "healthy",
    targetTraffic: 4100,
    botTraffic: 35,
    googleTag: null,
    conversion: null,
    cfZoneId: "zn_fake_004",
    palladiumCampaignId: "pc_004",
    lastScannedAt: "2026-03-26T21:50:00.000Z",
    createdAt: "2026-01-02T09:00:00.000Z",
    updatedAt: "2026-03-26T21:50:00.000Z",
  },
  {
    id: "d5",
    name: "diabcontrol-now.com",
    serverId: "s1",
    status: "INACTIVE",
    buyerTag: null,
    geo: "DE",
    offerName: "DiabControl",
    currentOfferId: "o4",
    offerFolder: "diabcontrol-m4n5o6",
    hasTag: false,
    hasConversion: false,
    isEmpty: false,
    healthStatus: "degraded",
    targetTraffic: 500,
    botTraffic: 3,
    googleTag: null,
    conversion: null,
    cfZoneId: null,
    palladiumCampaignId: null,
    lastScannedAt: "2026-03-25T18:00:00.000Z",
    createdAt: "2026-02-10T12:00:00.000Z",
    updatedAt: "2026-03-25T18:00:00.000Z",
  },
  {
    id: "d6",
    name: "slim-detox-life.com",
    serverId: "s1",
    status: "BANNED",
    buyerTag: "Alpha",
    geo: "LT",
    offerName: "SlimDetox",
    currentOfferId: "o5",
    offerFolder: "slimdetox-p7q8r9",
    hasTag: true,
    hasConversion: true,
    isEmpty: false,
    healthStatus: "down",
    targetTraffic: 150,
    botTraffic: 88,
    googleTag: "GT-XXXX6",
    conversion: "AW-XXXX6/ghi",
    cfZoneId: "zn_fake_006",
    palladiumCampaignId: "pc_006",
    lastScannedAt: "2026-03-24T10:00:00.000Z",
    createdAt: "2026-01-20T08:30:00.000Z",
    updatedAt: "2026-03-24T10:00:00.000Z",
  },
  {
    id: "d7",
    name: "wellbeing-formula.net",
    serverId: "s1",
    status: "ACTIVE",
    buyerTag: "Bravo",
    geo: "LV",
    offerName: "CardioBalance",
    currentOfferId: "o1",
    offerFolder: "cardiobalance-s1t2u3",
    hasTag: true,
    hasConversion: true,
    isEmpty: false,
    healthStatus: "healthy",
    targetTraffic: 2100,
    botTraffic: 5,
    googleTag: "GT-XXXX7",
    conversion: "AW-XXXX7/jkl",
    cfZoneId: "zn_fake_007",
    palladiumCampaignId: "pc_007",
    lastScannedAt: "2026-03-26T22:15:00.000Z",
    createdAt: "2026-02-01T15:00:00.000Z",
    updatedAt: "2026-03-26T22:15:00.000Z",
  },
  {
    id: "d8",
    name: "pure-vitality-shop.com",
    serverId: "s1",
    status: "INACTIVE",
    buyerTag: null,
    geo: "EE",
    offerName: null,
    currentOfferId: null,
    offerFolder: null,
    hasTag: false,
    hasConversion: false,
    isEmpty: true,
    healthStatus: "unknown",
    targetTraffic: 0,
    botTraffic: 0,
    googleTag: null,
    conversion: null,
    cfZoneId: null,
    palladiumCampaignId: null,
    lastScannedAt: null,
    createdAt: "2026-03-20T10:00:00.000Z",
    updatedAt: "2026-03-20T10:00:00.000Z",
  },

  // --- Server s2 (Production EU-West) - 8 domains ---
  {
    id: "d9",
    name: "gluconorm-health.com",
    serverId: "s2",
    status: "ACTIVE",
    buyerTag: "Bravo",
    geo: "DE",
    offerName: "DiabControl",
    currentOfferId: "o4",
    offerFolder: "diabcontrol-v4w5x6",
    hasTag: true,
    hasConversion: true,
    isEmpty: false,
    healthStatus: "healthy",
    targetTraffic: 3800,
    botTraffic: 15,
    googleTag: "GT-XXXX9",
    conversion: "AW-XXXX9/mno",
    cfZoneId: "zn_fake_009",
    palladiumCampaignId: "pc_009",
    lastScannedAt: "2026-03-26T23:00:00.000Z",
    createdAt: "2025-11-25T10:00:00.000Z",
    updatedAt: "2026-03-26T23:00:00.000Z",
  },
  {
    id: "d10",
    name: "flexijoint-store.net",
    serverId: "s2",
    status: "ACTIVE",
    buyerTag: "Alpha",
    geo: "PL",
    offerName: "JointFlex Pro",
    currentOfferId: "o3",
    offerFolder: "jointflex-y7z8a9",
    hasTag: true,
    hasConversion: false,
    isEmpty: false,
    healthStatus: "healthy",
    targetTraffic: 2900,
    botTraffic: 19,
    googleTag: "GT-XXXX10",
    conversion: null,
    cfZoneId: "zn_fake_010",
    palladiumCampaignId: "pc_010",
    lastScannedAt: "2026-03-26T23:05:00.000Z",
    createdAt: "2025-12-15T09:00:00.000Z",
    updatedAt: "2026-03-26T23:05:00.000Z",
  },
  {
    id: "d11",
    name: "brainboost-natural.com",
    serverId: "s2",
    status: "ACTIVE",
    buyerTag: "Bravo",
    geo: "EE",
    offerName: "NeuroTonic Plus",
    currentOfferId: "o2",
    offerFolder: "neurotonic-b1c2d3",
    hasTag: false,
    hasConversion: false,
    isEmpty: false,
    healthStatus: "degraded",
    targetTraffic: 1200,
    botTraffic: 45,
    googleTag: null,
    conversion: null,
    cfZoneId: "zn_fake_011",
    palladiumCampaignId: "pc_011",
    lastScannedAt: "2026-03-26T23:10:00.000Z",
    createdAt: "2026-01-05T11:00:00.000Z",
    updatedAt: "2026-03-26T23:10:00.000Z",
  },
  {
    id: "d12",
    name: "cardio-wellness.org",
    serverId: "s2",
    status: "ACTIVE",
    buyerTag: "Alpha",
    geo: "LV",
    offerName: "CardioBalance",
    currentOfferId: "o1",
    offerFolder: "cardiobalance-e4f5g6",
    hasTag: true,
    hasConversion: true,
    isEmpty: false,
    healthStatus: "healthy",
    targetTraffic: 4800,
    botTraffic: 7,
    googleTag: "GT-XXXX12",
    conversion: "AW-XXXX12/pqr",
    cfZoneId: "zn_fake_012",
    palladiumCampaignId: "pc_012",
    lastScannedAt: "2026-03-26T23:15:00.000Z",
    createdAt: "2025-12-20T16:00:00.000Z",
    updatedAt: "2026-03-26T23:15:00.000Z",
  },
  {
    id: "d13",
    name: "detox-slim-body.net",
    serverId: "s2",
    status: "INACTIVE",
    buyerTag: "Bravo",
    geo: "LT",
    offerName: "SlimDetox",
    currentOfferId: "o5",
    offerFolder: "slimdetox-h7i8j9",
    hasTag: false,
    hasConversion: false,
    isEmpty: false,
    healthStatus: "degraded",
    targetTraffic: 320,
    botTraffic: 2,
    googleTag: null,
    conversion: null,
    cfZoneId: null,
    palladiumCampaignId: null,
    lastScannedAt: "2026-03-25T14:00:00.000Z",
    createdAt: "2026-02-12T08:00:00.000Z",
    updatedAt: "2026-03-25T14:00:00.000Z",
  },
  {
    id: "d14",
    name: "heartguard-eu.com",
    serverId: "s2",
    status: "BANNED",
    buyerTag: "Alpha",
    geo: "LV",
    offerName: "CardioBalance",
    currentOfferId: "o1",
    offerFolder: "cardiobalance-k1l2m3",
    hasTag: true,
    hasConversion: true,
    isEmpty: false,
    healthStatus: "down",
    targetTraffic: 100,
    botTraffic: 95,
    googleTag: "GT-XXXX14",
    conversion: "AW-XXXX14/stu",
    cfZoneId: "zn_fake_014",
    palladiumCampaignId: "pc_014",
    lastScannedAt: "2026-03-23T09:00:00.000Z",
    createdAt: "2025-11-30T10:00:00.000Z",
    updatedAt: "2026-03-23T09:00:00.000Z",
  },
  {
    id: "d15",
    name: "naturalbalance-de.com",
    serverId: "s2",
    status: "ACTIVE",
    buyerTag: null,
    geo: "DE",
    offerName: "DiabControl",
    currentOfferId: "o4",
    offerFolder: "diabcontrol-n4o5p6",
    hasTag: true,
    hasConversion: false,
    isEmpty: false,
    healthStatus: "healthy",
    targetTraffic: 1650,
    botTraffic: 11,
    googleTag: "GT-XXXX15",
    conversion: null,
    cfZoneId: "zn_fake_015",
    palladiumCampaignId: null,
    lastScannedAt: "2026-03-26T23:20:00.000Z",
    createdAt: "2026-02-20T13:00:00.000Z",
    updatedAt: "2026-03-26T23:20:00.000Z",
  },
  {
    id: "d16",
    name: "vitafit-europe.net",
    serverId: "s2",
    status: "INACTIVE",
    buyerTag: null,
    geo: "PL",
    offerName: null,
    currentOfferId: null,
    offerFolder: null,
    hasTag: false,
    hasConversion: false,
    isEmpty: true,
    healthStatus: "unknown",
    targetTraffic: 0,
    botTraffic: 0,
    googleTag: null,
    conversion: null,
    cfZoneId: null,
    palladiumCampaignId: null,
    lastScannedAt: null,
    createdAt: "2026-03-22T10:00:00.000Z",
    updatedAt: "2026-03-22T10:00:00.000Z",
  },

  // --- Server s3 (Staging) - 4 domains ---
  {
    id: "d17",
    name: "test-offer-alpha.dev",
    serverId: "s3",
    status: "ACTIVE",
    buyerTag: "Alpha",
    geo: "LV",
    offerName: "CardioBalance",
    currentOfferId: "o1",
    offerFolder: "cardiobalance-test01",
    hasTag: false,
    hasConversion: false,
    isEmpty: false,
    healthStatus: "healthy",
    targetTraffic: 250,
    botTraffic: 0,
    googleTag: null,
    conversion: null,
    cfZoneId: null,
    palladiumCampaignId: null,
    lastScannedAt: "2026-03-26T20:00:00.000Z",
    createdAt: "2026-03-01T10:00:00.000Z",
    updatedAt: "2026-03-26T20:00:00.000Z",
  },
  {
    id: "d18",
    name: "staging-neuro.dev",
    serverId: "s3",
    status: "ACTIVE",
    buyerTag: "Bravo",
    geo: "EE",
    offerName: "NeuroTonic Plus",
    currentOfferId: "o2",
    offerFolder: "neurotonic-test02",
    hasTag: true,
    hasConversion: true,
    isEmpty: false,
    healthStatus: "healthy",
    targetTraffic: 180,
    botTraffic: 1,
    googleTag: "GT-TEST18",
    conversion: "AW-TEST18/xyz",
    cfZoneId: null,
    palladiumCampaignId: null,
    lastScannedAt: "2026-03-26T20:05:00.000Z",
    createdAt: "2026-03-05T14:00:00.000Z",
    updatedAt: "2026-03-26T20:05:00.000Z",
  },
  {
    id: "d19",
    name: "preview-joint.dev",
    serverId: "s3",
    status: "BANNED",
    buyerTag: null,
    geo: "PL",
    offerName: "JointFlex Pro",
    currentOfferId: "o3",
    offerFolder: "jointflex-test03",
    hasTag: false,
    hasConversion: false,
    isEmpty: false,
    healthStatus: "down",
    targetTraffic: 0,
    botTraffic: 72,
    googleTag: null,
    conversion: null,
    cfZoneId: null,
    palladiumCampaignId: null,
    lastScannedAt: "2026-03-24T16:00:00.000Z",
    createdAt: "2026-03-10T09:30:00.000Z",
    updatedAt: "2026-03-24T16:00:00.000Z",
  },
  {
    id: "d20",
    name: "sandbox-slim.dev",
    serverId: "s3",
    status: "INACTIVE",
    buyerTag: "Alpha",
    geo: "LT",
    offerName: null,
    currentOfferId: null,
    offerFolder: null,
    hasTag: false,
    hasConversion: false,
    isEmpty: true,
    healthStatus: "unknown",
    targetTraffic: 0,
    botTraffic: 0,
    googleTag: null,
    conversion: null,
    cfZoneId: null,
    palladiumCampaignId: null,
    lastScannedAt: null,
    createdAt: "2026-03-18T11:00:00.000Z",
    updatedAt: "2026-03-18T11:00:00.000Z",
  },
];

// ---------------------------------------------------------------------------
// Jobs (10 entries)
// ---------------------------------------------------------------------------

export let jobs: any[] = [
  {
    id: "j1",
    kind: "DISCOVER",
    status: "success",
    serverId: "s1",
    domainId: null,
    payload: { serverName: "Production US-East" },
    result: { domainsFound: 8, newDomains: 2 },
    progress: 100,
    errorMessage: null,
    attempt: 1,
    maxAttempts: 3,
    nextRetryAt: null,
    lastError: null,
    startedAt: "2026-03-26T18:00:00.000Z",
    finishedAt: "2026-03-26T18:02:30.000Z",
    createdById: "u1",
    createdAt: "2026-03-26T17:59:50.000Z",
  },
  {
    id: "j2",
    kind: "APPLY_OFFER_TO_DOMAIN",
    status: "success",
    serverId: "s1",
    domainId: "d1",
    payload: { offerId: "o1", domainName: "healthvita-plus.com" },
    result: { deployed: true, offerName: "CardioBalance" },
    progress: 100,
    errorMessage: null,
    attempt: 1,
    maxAttempts: 3,
    nextRetryAt: null,
    lastError: null,
    startedAt: "2026-03-26T19:00:00.000Z",
    finishedAt: "2026-03-26T19:01:45.000Z",
    createdById: "u2",
    createdAt: "2026-03-26T18:59:50.000Z",
  },
  {
    id: "j3",
    kind: "DEPLOY_DOMAINS",
    status: "running",
    serverId: "s2",
    domainId: null,
    payload: {
      domainIds: ["d9", "d10", "d11"],
      offerId: "o4",
      geo: "DE",
    },
    result: null,
    progress: 42,
    errorMessage: null,
    attempt: 1,
    maxAttempts: 3,
    nextRetryAt: null,
    lastError: null,
    startedAt: "2026-03-27T09:30:00.000Z",
    finishedAt: null,
    createdById: "u1",
    createdAt: "2026-03-27T09:29:50.000Z",
  },
  {
    id: "j4",
    kind: "TAG_INSERT",
    status: "failed",
    serverId: "s2",
    domainId: "d11",
    payload: {
      domainName: "brainboost-natural.com",
      googleTag: "GT-FAIL1",
    },
    result: null,
    progress: 60,
    errorMessage: "SSH connection timed out after 30s",
    attempt: 3,
    maxAttempts: 3,
    nextRetryAt: null,
    lastError: "SSH connection timed out after 30s",
    startedAt: "2026-03-26T15:00:00.000Z",
    finishedAt: "2026-03-26T15:00:35.000Z",
    createdById: "u3",
    createdAt: "2026-03-26T14:59:50.000Z",
  },
  {
    id: "j5",
    kind: "APPLY_OFFER_TO_DOMAIN",
    status: "running",
    serverId: "s1",
    domainId: "d4",
    payload: { offerId: "o3", domainName: "jointflex-pro.com" },
    result: null,
    progress: 78,
    errorMessage: null,
    attempt: 1,
    maxAttempts: 3,
    nextRetryAt: null,
    lastError: null,
    startedAt: "2026-03-27T09:45:00.000Z",
    finishedAt: null,
    createdById: "u2",
    createdAt: "2026-03-27T09:44:50.000Z",
  },
  {
    id: "j6",
    kind: "DISCOVER",
    status: "success",
    serverId: "s2",
    domainId: null,
    payload: { serverName: "Production EU-West" },
    result: { domainsFound: 8, newDomains: 0 },
    progress: 100,
    errorMessage: null,
    attempt: 1,
    maxAttempts: 3,
    nextRetryAt: null,
    lastError: null,
    startedAt: "2026-03-26T16:00:00.000Z",
    finishedAt: "2026-03-26T16:01:10.000Z",
    createdById: "u1",
    createdAt: "2026-03-26T15:59:50.000Z",
  },
  {
    id: "j7",
    kind: "SCAN_DEPLOYMENT_STATUS",
    status: "queued",
    serverId: "s1",
    domainId: null,
    payload: { scope: "all" },
    result: null,
    progress: 0,
    errorMessage: null,
    attempt: 0,
    maxAttempts: 3,
    nextRetryAt: null,
    lastError: null,
    startedAt: null,
    finishedAt: null,
    createdById: "u1",
    createdAt: "2026-03-27T10:00:00.000Z",
  },
  {
    id: "j8",
    kind: "DEPLOY_DOMAINS",
    status: "failed",
    serverId: "s3",
    domainId: null,
    payload: {
      domainIds: ["d17", "d19"],
      offerId: "o1",
      geo: "LV",
    },
    result: {
      succeeded: 1,
      failed: 1,
      details: [
        { domainId: "d17", status: "success" },
        {
          domainId: "d19",
          status: "failed",
          error: "Palladium cloak deployment failed: Campaign creation timeout",
          rollbackStatus: "SUCCESS",
        },
      ],
    },
    progress: 100,
    errorMessage: "1 of 2 domains failed to deploy",
    attempt: 1,
    maxAttempts: 3,
    nextRetryAt: "2026-03-27T10:15:00.000Z",
    lastError: "1 of 2 domains failed to deploy",
    startedAt: "2026-03-27T08:00:00.000Z",
    finishedAt: "2026-03-27T08:03:20.000Z",
    createdById: "u3",
    createdAt: "2026-03-27T07:59:50.000Z",
  },
  {
    id: "j9",
    kind: "TAG_INSERT",
    status: "queued",
    serverId: "s2",
    domainId: "d15",
    payload: {
      domainName: "naturalbalance-de.com",
      googleTag: "GT-NEW15",
      conversion: "AW-NEW15/conv",
    },
    result: null,
    progress: 0,
    errorMessage: null,
    attempt: 0,
    maxAttempts: 3,
    nextRetryAt: null,
    lastError: null,
    startedAt: null,
    finishedAt: null,
    createdById: "u2",
    createdAt: "2026-03-27T10:05:00.000Z",
  },
  {
    id: "j10",
    kind: "APPLY_OFFER_TO_DOMAIN",
    status: "cancelled",
    serverId: "s2",
    domainId: "d13",
    payload: { offerId: "o5", domainName: "detox-slim-body.net" },
    result: null,
    progress: 15,
    errorMessage: "Cancelled by user",
    attempt: 1,
    maxAttempts: 3,
    nextRetryAt: null,
    lastError: "Cancelled by user",
    startedAt: "2026-03-26T12:00:00.000Z",
    finishedAt: "2026-03-26T12:00:20.000Z",
    createdById: "u3",
    createdAt: "2026-03-26T11:59:50.000Z",
  },
];

// ---------------------------------------------------------------------------
// Global Settings
// ---------------------------------------------------------------------------

export let settings: Record<string, string> = {
  whiteBasePrefix: "/var/www/",
  offerSubfolder: "product",
  crmScriptPaths: JSON.stringify(["/var/www/{domain}/product/core.php"]),
  palladiumCloakingEnabled: "true",
  domainCost: "7.20",
  maintenanceMode: "false",
};

// ---------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------

export let notifications: any[] = [
  {
    id: "n1",
    type: "HEALTH_ALERT",
    title: "Domain down: slim-detox-life.com",
    message:
      "Health check failed for slim-detox-life.com. Domain returned HTTP 503 for 3 consecutive checks.",
    severity: "critical",
    read: false,
    domainId: "d6",
    serverId: "s1",
    createdAt: "2026-03-27T08:30:00.000Z",
  },
  {
    id: "n2",
    type: "HEALTH_ALERT",
    title: "High bot traffic: heartguard-eu.com",
    message:
      "Bot traffic ratio for heartguard-eu.com has exceeded 90%. Current ratio: 95%. Consider investigating.",
    severity: "warning",
    read: false,
    domainId: "d14",
    serverId: "s2",
    createdAt: "2026-03-27T07:15:00.000Z",
  },
  {
    id: "n3",
    type: "SYSTEM",
    title: "Deployment completed",
    message:
      "Bulk deployment to Production EU-West completed: 3 domains processed, 2 succeeded, 1 failed.",
    severity: "info",
    read: true,
    domainId: null,
    serverId: "s2",
    createdAt: "2026-03-27T08:03:30.000Z",
  },
  {
    id: "n4",
    type: "HEALTH_ALERT",
    title: "Domain degraded: brainboost-natural.com",
    message:
      "Response time for brainboost-natural.com has increased to 4.2s (threshold: 2s). Performance degraded.",
    severity: "warning",
    read: true,
    domainId: "d11",
    serverId: "s2",
    createdAt: "2026-03-26T22:45:00.000Z",
  },
  {
    id: "n5",
    type: "SYSTEM",
    title: "Scheduled scan completed",
    message:
      "Daily domain scan completed for all servers. 20 domains scanned, 0 new issues detected.",
    severity: "info",
    read: true,
    domainId: null,
    serverId: null,
    createdAt: "2026-03-26T06:00:00.000Z",
  },
];

// ---------------------------------------------------------------------------
// Audit log
// ---------------------------------------------------------------------------

export let audits: any[] = [
  {
    id: "a1",
    action: "OFFER_DEPLOYED",
    userId: "u2",
    username: "alex_operator",
    targetType: "domain",
    targetId: "d1",
    targetName: "healthvita-plus.com",
    details: "Deployed offer CardioBalance to healthvita-plus.com",
    ipAddress: "203.0.113.50",
    createdAt: "2026-03-26T19:01:45.000Z",
  },
  {
    id: "a2",
    action: "DOMAIN_STATUS_CHANGED",
    userId: "u1",
    username: "admin",
    targetType: "domain",
    targetId: "d6",
    targetName: "slim-detox-life.com",
    details: "Status changed from ACTIVE to BANNED (high bot traffic detected)",
    ipAddress: "203.0.113.50",
    createdAt: "2026-03-26T14:30:00.000Z",
  },
  {
    id: "a3",
    action: "SERVER_DISCOVERED",
    userId: "u1",
    username: "admin",
    targetType: "server",
    targetId: "s1",
    targetName: "Production US-East",
    details: "Domain discovery completed: 8 domains found, 2 new domains added",
    ipAddress: "203.0.113.50",
    createdAt: "2026-03-26T18:02:30.000Z",
  },
  {
    id: "a4",
    action: "USER_CREATED",
    userId: "u1",
    username: "admin",
    targetType: "user",
    targetId: "u3",
    targetName: "maria_ops",
    details: "Created new OPERATOR user maria_ops with buyerTag Bravo",
    ipAddress: "203.0.113.50",
    createdAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "a5",
    action: "SETTINGS_UPDATED",
    userId: "u1",
    username: "admin",
    targetType: "setting",
    targetId: "domainCost",
    targetName: "domainCost",
    details: "Global setting domainCost changed from 5.00 to 7.20",
    ipAddress: "203.0.113.50",
    createdAt: "2026-03-25T10:15:00.000Z",
  },
];
